version: "3.7"

services:
  api:
    container_name: bench_api_dev
    image: bench_api_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8000"
    env_file:
      - .env
    restart: on-failure:3
